### ISSUE TITLE
No Beatmap Hitsounds on sliders

### ISSUE THREAD

**Issue by HeyItsJinx** [swoolcock/rush#112]
So i was vibin on a song and noticed that on the sliders specifically, the sliders dont register as a hitsound for some reason. ive tried using different skins to see if that makes a difference and it does not.

https://drive.google.com/file/d/1KiaoMgbxvwONn6leYVybEnOYP7XnvZMi/view?usp=sharing

might have to download video since its a minute long and my drive is playing up.

**Comment by LumpBloom7** [comment]
Okay. I looked through the video, and it looks like some of the std sliders lack a hitsounds for the tail. And by the looks of it, the rush conversion respects that. (specifically comparing the first, fourth and seventh, since they lack a tail sound)

**Comment by HeyItsJinx** [comment]
if i may ask. i dont really understand what u mean. i get its in the conversion thing. but is it going to be liked re done at all? so it works with correct hitsounds? it does it on other songs to. everything will freeze max diff also.

**Comment by LumpBloom7** [comment]
It is working with the correct hitsounds is what I'm trying to say. Listen closely to the slider tails in the original map, you'll notice that some of them doesn't have any hitsounds.

**Comment by HeyItsJinx** [comment]
> It is working with the correct hitsounds is what I'm trying to say. Listen closely to the slider tails in the original map, you'll notice that some of them doesn't have any hitsounds.

Im still confused because if i look at where same notes are on standard. The hitsounds play. But on rush when goin to same note if its a slider. There isnt any hitsound for it. May i ask if u can get the map shown and test it for ureself? Ik the skin hit is playin but not the custom one inplemented for that song.

**Comment by LumpBloom7** [comment]
Ok now I realize what you meant; I was looking at the wrong place, since the issue title mentioned specifically sliders, when it is all notes.

**Comment by HeyItsJinx** [comment]
understood. my apologies for not explaning more specific
