### ISSUE TITLE
To be more like Muse Dash

### ISSUE THREAD

**Issue by Cryptises** [swoolcock/rush#121]
* Notes don't miss for hitting too early (sliders too)
* Hearts aren't actually something you need to physically hit (only collide)
* Each note that damages the player takes 20 hp respectively, spikes take 30
* Map speed can vary overtime (dependent on song)
* +Ghosts, don't necessarily need to hit them but does add to combo 0 penalty for not hitting (unless they're directly next to a note)

**Comment by swoolcock** [comment]
The goal is not to be too close to Muse Dash.  While I'd like for some of these to be implemented, they won't be called or function the same way.

**Comment by frenzibyte** [comment]
Does this still need to be open? maybe can be moved to #1 or track each actual issue separately.

**Comment by swoolcock** [comment]
I think it’s probably trivial enough to close.
