### ISSUE TITLE
Slider lane does not need release of key at end

### ISSUE THREAD

**Issue by CNate140** [swoolcock/rush#13]
Not sure if this is where a request goes, but is it intended to get a perfect if you do not release the key at end of a slider lane? Never used github so feel free to delete if this is in the wrong location.

**Comment by recapitalverb** [comment]
If you have played any amount of Muse Dash before, you can answer this yourself. And yes, it is intended that you get a Perfect if you do not release the key at end of a slider.

**Comment by swoolcock** [comment]
Unintended actually, I’m considering changing it to a Great if you don’t release.  osu!mania players will certainly expect it.

**Comment by recapitalverb** [comment]
My previous comment might have been a bit uncalled for, but I doubt changing it to a Great if the player doesn't release would improve gameplay. I think it's more comfortable for Muse Dash players if we just let things be like right now.

**Comment by swoolcock** [comment]
No problem, it was easier to keep it in the Muse Dash perfect fashion anyway as it solved a visual issue that was keeping the tail star visible when it shouldn't be.
