### ISSUE TITLE
Bug with the blue notes

### ISSUE THREAD

**Issue by AsierFX** [swoolcock/rush#20]
When i hit a blue note, or i jump, i cant jump in a lot of time. And a lot of times happens that with a two keys (blue and red at the same time) and later a stream with blue notes and 3 or 4 notes i cant press because of that error. Please fix it xd

**Comment by frenzibyte** [comment]
Please attach a link to the beatmap you're encountering this on, also showcasing the bug in a video **with the key overlay displayed on** would be highly better.
