### ISSUE TITLE
rush! gamemode crashing on fresh installation

### ISSUE THREAD

**Issue by ari-outi** [swoolcock/rush#38]
no default settings changed but as soon as the first note is ready to hit, the game will freeze and crash instantly.

**Comment by frenzibyte** [comment]
Can reproduce, seems to be related to the latest osu! judgement changes.

**Comment by frenzibyte** [comment]
@ari-outi The issue has been fixed! you can try the latest release now: https://github.com/swoolcock/rush/releases/tag/2020.711.0
