### ISSUE TITLE
Discord and Donations?

### ISSUE THREAD

**Issue by oscmkv** [swoolcock/rush#42]
Sorry if this is not the correct place to suggest this, but would it be possible to get a Discord server created for the custom mode for bug finding, suggestion adding, play sharing, map creation, and future skinning?

Also, is there a way to help fund this project? I would full heartedly support osu!rush and help make sure it keeps getting good updates. As someone who has invested a lot of time into Muse Dash I would love to see this custom mode flourish.

**Comment by swoolcock** [comment]
I'm currently focused on osu!framework so I haven't had much time to look at Rush! recently.  I've mostly been fixing or approving PRs to ensure it works with recent osu! changes.

Is there actually enough of a community for a Discord server?  Also it's more about time and cognitive load rather than money, so I'd rather not take any kind of donations.

**Comment by oscmkv** [comment]
> I'm currently focused on osu!framework so I haven't had much time to look at Rush! recently. I've mostly been fixing or approving PRs to ensure it works with recent osu! changes.
> 
> Is there actually enough of a community for a Discord server? Also it's more about time and cognitive load rather than money, so I'd rather not take any kind of donations.

I feel like there could be. There's countless of people in the MD community who would want custom charts and this game mode is pretty well fleshed out from what I've seen so far. It shouldn't be too hard to get people to come together once they know it exists.

**Comment by swoolcock** [comment]
There is now a Discord invite link in the readme.  Feel free to join if you want to chat about development, project direction etc.
