### ISSUE TITLE
More Inputs Should Be Allowed

### ISSUE THREAD

**Issue by oscmkv** [swoolcock/rush#43]
Currently there are only two available input keys for each Ground and Air. This is fine and all until you get to 4* and higher rated charts where streams start to become more of a driving factor in difficulty. I think at least 8 Keys in total 4 for Air and 4 for Ground would make higher star rating maps more beatable. Especially players who would be coming from Muse Dash and might not be used to Taiko styled keyboard input limitations with only 2 keys for each lane.

**Comment by swoolcock** [comment]
I wasn't aware that Muse Dash allowed more than 2 keys per lane.  I should be able to do that.

**Comment by frenzibyte** [comment]
Sounds straightforward to me, marking as "good first issue".
