### ISSUE TITLE
Beatmap conversion bug

### ISSUE THREAD

**Issue by Rextttt** [swoolcock/rush#74]
I was playing on this beatmap (Koa%wer difficulty), and in the middle of the song a couple of the sliders start breaking:
https://osu.ppy.sh/beatmapsets/639281#osu/1355907

Heres a clip of what happens:
https://www.twitch.tv/videos/769439574?t=00h01m08s

^^^ that timestamp should work, but feel free to @ me in the discord if it stops working for some reason (Rext#7043)

I'm on osu!lazer version 2020.1009.0 and the newest version of rush

**Comment by swoolcock** [comment]
Hmmm very strange, does it do it with previous versions of osu!?

**Comment by swoolcock** [comment]
Right... I just watched an autoplay of that song on osu!standard. Watch what happens in the slider art in that song and you'll understand why this is being closed "won't fix".  :)

**Comment by swoolcock** [comment]
<img width="1185" alt="Screen Shot 2020-10-14 at 8 24 08 pm" src="https://user-images.githubusercontent.com/2331297/95973522-4fe2ab80-0e5b-11eb-9e91-020458a5c5c1.png">
